[build]
  command = "npm run build"
  publish = "build"

[[integrations]]
  name = "netlify-plugin-chatbees"

[integrations.dev]
  # Set the "path" as the path from your test site to your integration's build folder.
  path = "../netlify-plugin-chatbees"
  # The following forces the integration to be used when building the test site.
  force_run_in_build = true

[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 301
  force = true
